name: Build & Publish (master)

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - run: docker build -t ghcr.io/leo40git/picartostreamnotifier:latest -t ghcr.io/leo40git/picartostreamnotifier:${GITHUB_SHA} .
      - run: docker push ghcr.io/leo40git/picartostreamnotifier:latest
      - run: docker push ghcr.io/leo40git/picartostreamnotifier:${GITHUB_SHA}
